eval_model_id = "Nat1an/cerulean-lab5-muon-pilot-j511584"
training_run_url = "https://wandb.ai/cerulean-labs/lab5-training-llama/runs/kyzatb1t"

training_config = {
    "optimizer": {
        "name": "Muon + AdamW",
        "learning_rate": 0.001,
        "groups": "Muon: hidden matrices; AdamW: tied embedding and norms",
        "weight_decay": 0.1,
        "normalization_weight_decay": 0.0,
        "momentum": 0.95,
        "nesterov": True,
        "ns_steps": 5,
        "adjust_lr_fn": "match_rms_adamw",
        "adamw_betas": [0.9, 0.95],
        "adamw_eps": 1e-8,
    },
    "schedule": "400-step linear warmup, cosine to zero at step 8000",
    "context_length": 8192,
    "initialization": "random",
    "dataset": "allenai/dolma3_mix-150B-1025",
    "shuffle_seed": 42,
    "holdout_documents": 50000,
    "holdout_excluded_from_training": True,
    "non_padding_tokens_seen": 2062548992,
    "repeated_tokens_counted": True,
    "duration_seconds": 6624,
    "gpu_type": "H200",
    "gpu_count": 8,
    "validation_documents": 1024,
    "micro_batch_size": 1,
    "gradient_accumulation_steps": 4,
    "effective_batch_tokens": 262144,
    "completed_steps": 7868,
    "max_grad_norm": 1.0,
}
